//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS_web.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledMeter : Meter
    {
        public System.DateTime InstallDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    }
}
