//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS_web.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer1 : DbContext
    {
        public ModelContainer1()
            : base("name=ModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meter> MeterSet { get; set; }
        public virtual DbSet<Parametr> ParametrSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Document> DocumentSet { get; set; }
        public virtual DbSet<Tariff> TariffSet { get; set; }
        public virtual DbSet<TimeSpan> TimeSpanSet { get; set; }
        public virtual DbSet<Reading> ReadingSet { get; set; }
    }
}
